// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentManagementSystem.DAL.Data;

#nullable disable

namespace StudentManagementSystem.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260130063836_RenameAttendanceToQuiz")]
    partial class RenameAttendanceToQuiz
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentManagementSystem.DAL.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("MajorId")
                        .HasColumnType("int");

                    b.Property<int?>("PrerequisiteCourseId")
                        .HasColumnType("int");

                    b.Property<int>("SemesterNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("TuitionFee")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CourseId");

                    b.HasIndex("CourseCode")
                        .IsUnique();

                    b.HasIndex("MajorId");

                    b.HasIndex("PrerequisiteCourseId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            CourseCode = "IT101",
                            CourseName = "Nhập môn Lập trình",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Credits = 3,
                            Description = "Học C# cơ bản",
                            MajorId = 1,
                            SemesterNumber = 1,
                            TuitionFee = 2000000m
                        },
                        new
                        {
                            CourseId = 2,
                            CourseCode = "IT102",
                            CourseName = "Toán rời rạc",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Credits = 3,
                            Description = "Logic, tập hợp, đồ thị",
                            MajorId = 1,
                            SemesterNumber = 1,
                            TuitionFee = 1500000m
                        },
                        new
                        {
                            CourseId = 3,
                            CourseCode = "IT103",
                            CourseName = "Cơ sở dữ liệu",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Credits = 3,
                            Description = "SQL Server cơ bản",
                            MajorId = 1,
                            SemesterNumber = 1,
                            TuitionFee = 2000000m
                        },
                        new
                        {
                            CourseId = 4,
                            CourseCode = "IT104",
                            CourseName = "Anh văn IT 1",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Credits = 2,
                            Description = "English for IT",
                            MajorId = 1,
                            SemesterNumber = 1,
                            TuitionFee = 1000000m
                        },
                        new
                        {
                            CourseId = 5,
                            CourseCode = "ENG101",
                            CourseName = "Grammar Foundation",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Credits = 3,
                            MajorId = 2,
                            SemesterNumber = 1,
                            TuitionFee = 1500000m
                        },
                        new
                        {
                            CourseId = 6,
                            CourseCode = "ENG102",
                            CourseName = "Listening Skills",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Credits = 3,
                            MajorId = 2,
                            SemesterNumber = 1,
                            TuitionFee = 1500000m
                        },
                        new
                        {
                            CourseId = 7,
                            CourseCode = "ENG103",
                            CourseName = "Speaking Skills",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Credits = 3,
                            MajorId = 2,
                            SemesterNumber = 1,
                            TuitionFee = 1500000m
                        },
                        new
                        {
                            CourseId = 8,
                            CourseCode = "ENG104",
                            CourseName = "Phonetics",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Credits = 2,
                            MajorId = 2,
                            SemesterNumber = 1,
                            TuitionFee = 1000000m
                        },
                        new
                        {
                            CourseId = 9,
                            CourseCode = "BUS101",
                            CourseName = "Nguyên lý Kinh tế",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Credits = 3,
                            MajorId = 3,
                            SemesterNumber = 1,
                            TuitionFee = 1500000m
                        },
                        new
                        {
                            CourseId = 10,
                            CourseCode = "BUS102",
                            CourseName = "Quản trị học",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Credits = 3,
                            MajorId = 3,
                            SemesterNumber = 1,
                            TuitionFee = 1500000m
                        },
                        new
                        {
                            CourseId = 11,
                            CourseCode = "BUS103",
                            CourseName = "Kế toán cơ bản",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Credits = 3,
                            MajorId = 3,
                            SemesterNumber = 1,
                            TuitionFee = 1500000m
                        },
                        new
                        {
                            CourseId = 12,
                            CourseCode = "BUS104",
                            CourseName = "Anh văn Thương mại",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Credits = 2,
                            MajorId = 3,
                            SemesterNumber = 1,
                            TuitionFee = 1000000m
                        },
                        new
                        {
                            CourseId = 13,
                            CourseCode = "IT201",
                            CourseName = "Cấu trúc dữ liệu",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Credits = 4,
                            Description = "Stack, Queue, Tree",
                            MajorId = 1,
                            PrerequisiteCourseId = 1,
                            SemesterNumber = 2,
                            TuitionFee = 2500000m
                        },
                        new
                        {
                            CourseId = 14,
                            CourseCode = "IT202",
                            CourseName = "Lập trình OOP",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Credits = 4,
                            Description = "C# OOP nâng cao",
                            MajorId = 1,
                            PrerequisiteCourseId = 1,
                            SemesterNumber = 2,
                            TuitionFee = 2500000m
                        },
                        new
                        {
                            CourseId = 15,
                            CourseCode = "IT203",
                            CourseName = "SQL Server Nâng cao",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Credits = 3,
                            Description = "Stored Procedure, Trigger",
                            MajorId = 1,
                            PrerequisiteCourseId = 3,
                            SemesterNumber = 2,
                            TuitionFee = 2000000m
                        },
                        new
                        {
                            CourseId = 16,
                            CourseCode = "IT204",
                            CourseName = "Anh văn IT 2",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Credits = 2,
                            MajorId = 1,
                            PrerequisiteCourseId = 4,
                            SemesterNumber = 2,
                            TuitionFee = 1000000m
                        },
                        new
                        {
                            CourseId = 17,
                            CourseCode = "ENG201",
                            CourseName = "Advanced Grammar",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Credits = 3,
                            MajorId = 2,
                            PrerequisiteCourseId = 5,
                            SemesterNumber = 2,
                            TuitionFee = 1500000m
                        },
                        new
                        {
                            CourseId = 18,
                            CourseCode = "ENG202",
                            CourseName = "Reading Comprehension",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Credits = 3,
                            MajorId = 2,
                            PrerequisiteCourseId = 6,
                            SemesterNumber = 2,
                            TuitionFee = 1500000m
                        },
                        new
                        {
                            CourseId = 19,
                            CourseCode = "ENG203",
                            CourseName = "Writing Skills",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Credits = 3,
                            MajorId = 2,
                            PrerequisiteCourseId = 7,
                            SemesterNumber = 2,
                            TuitionFee = 1500000m
                        },
                        new
                        {
                            CourseId = 20,
                            CourseCode = "ENG204",
                            CourseName = "English Literature",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Credits = 2,
                            MajorId = 2,
                            SemesterNumber = 2,
                            TuitionFee = 1000000m
                        },
                        new
                        {
                            CourseId = 21,
                            CourseCode = "BUS201",
                            CourseName = "Marketing căn bản",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Credits = 3,
                            MajorId = 3,
                            PrerequisiteCourseId = 10,
                            SemesterNumber = 2,
                            TuitionFee = 1500000m
                        },
                        new
                        {
                            CourseId = 22,
                            CourseCode = "BUS202",
                            CourseName = "Quản trị Nhân sự",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Credits = 3,
                            MajorId = 3,
                            PrerequisiteCourseId = 10,
                            SemesterNumber = 2,
                            TuitionFee = 1500000m
                        },
                        new
                        {
                            CourseId = 23,
                            CourseCode = "BUS203",
                            CourseName = "Tài chính Doanh nghiệp",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Credits = 3,
                            MajorId = 3,
                            PrerequisiteCourseId = 11,
                            SemesterNumber = 2,
                            TuitionFee = 1500000m
                        },
                        new
                        {
                            CourseId = 24,
                            CourseCode = "BUS204",
                            CourseName = "Thống kê Kinh doanh",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Credits = 2,
                            MajorId = 3,
                            SemesterNumber = 2,
                            TuitionFee = 1000000m
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.DAL.Models.CourseClass", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassId"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentEnrollment")
                        .HasColumnType("int");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<int?>("InstructorId")
                        .HasColumnType("int");

                    b.Property<int>("MaxStudents")
                        .HasColumnType("int");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Schedule")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ClassId");

                    b.HasIndex("ClassName")
                        .IsUnique();

                    b.HasIndex("CourseId");

                    b.HasIndex("InstructorId");

                    b.HasIndex("SemesterId");

                    b.ToTable("CourseClasses");
                });

            modelBuilder.Entity("StudentManagementSystem.DAL.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentId"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DroppedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRetake")
                        .HasColumnType("bit");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SemesterId")
                        .HasColumnType("int");

                    b.Property<int>("SemesterNumber")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("ClassId");

                    b.HasIndex("CourseId");

                    b.HasIndex("SemesterId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("StudentManagementSystem.DAL.Models.Grade", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeId"));

                    b.Property<decimal>("AssignmentScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("int");

                    b.Property<decimal>("FinalExamScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("FinalScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("GradePoint")
                        .HasColumnType("decimal(3,2)");

                    b.Property<DateTime?>("GradedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPassed")
                        .HasColumnType("bit");

                    b.Property<string>("LetterGrade")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<decimal>("MidtermScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("QuizScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("GradeId");

                    b.HasIndex("CourseId");

                    b.HasIndex("EnrollmentId")
                        .IsUnique();

                    b.HasIndex("StudentId");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("StudentManagementSystem.DAL.Models.Instructor", b =>
                {
                    b.Property<int>("InstructorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstructorId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("InstructorCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Qualifications")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Specialization")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("InstructorId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("InstructorCode")
                        .IsUnique();

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            InstructorId = 1,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nva@university.edu.vn",
                            FullName = "Nguyễn Văn An",
                            InstructorCode = "GV001",
                            Phone = "0901234567",
                            Qualifications = "Thạc sĩ CNTT",
                            Specialization = "Database, Programming",
                            Status = "Active"
                        },
                        new
                        {
                            InstructorId = 2,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ttb@university.edu.vn",
                            FullName = "Trần Thị Bình",
                            InstructorCode = "GV002",
                            Phone = "0901234568",
                            Qualifications = "Tiến sĩ CNTT",
                            Specialization = "Web Development, OOP",
                            Status = "Active"
                        },
                        new
                        {
                            InstructorId = 3,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lvc@university.edu.vn",
                            FullName = "Lê Văn Cường",
                            InstructorCode = "GV003",
                            Phone = "0901234569",
                            Qualifications = "Thạc sĩ CNTT",
                            Specialization = "Data Structures, Algorithms",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.DAL.Models.InstructorAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<int>("AssignedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<int>("SemesterNumber")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("AssignmentId");

                    b.HasIndex("CourseId");

                    b.HasIndex("InstructorId");

                    b.ToTable("InstructorAssignments");
                });

            modelBuilder.Entity("StudentManagementSystem.DAL.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TransactionId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("InvoiceId");

                    b.HasIndex("StudentId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("StudentManagementSystem.DAL.Models.Major", b =>
                {
                    b.Property<int>("MajorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MajorId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DurationYears")
                        .HasColumnType("int");

                    b.Property<string>("MajorCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MajorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TotalCredits")
                        .HasColumnType("int");

                    b.Property<int>("TotalSemesters")
                        .HasColumnType("int");

                    b.HasKey("MajorId");

                    b.HasIndex("MajorCode")
                        .IsUnique();

                    b.ToTable("Majors");

                    b.HasData(
                        new
                        {
                            MajorId = 1,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Đào tạo kỹ sư phần mềm, lập trình viên",
                            DurationYears = 3,
                            MajorCode = "IT",
                            MajorName = "Công nghệ Thông tin",
                            TotalCredits = 108,
                            TotalSemesters = 9
                        },
                        new
                        {
                            MajorId = 2,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Đào tạo giáo viên tiếng Anh, biên phiên dịch",
                            DurationYears = 3,
                            MajorCode = "ENG",
                            MajorName = "Ngôn ngữ Anh",
                            TotalCredits = 108,
                            TotalSemesters = 9
                        },
                        new
                        {
                            MajorId = 3,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Đào tạo nhà quản trị doanh nghiệp",
                            DurationYears = 3,
                            MajorCode = "BUS",
                            MajorName = "Quản trị Kinh doanh",
                            TotalCredits = 108,
                            TotalSemesters = 9
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.DAL.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("ActionUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ReadDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("StudentManagementSystem.DAL.Models.PendingEnrollment", b =>
                {
                    b.Property<int>("PendingEnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PendingEnrollmentId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRetake")
                        .HasColumnType("bit");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RegisteredDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("RequiredFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SemesterNumber")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("PendingEnrollmentId");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("PendingEnrollments");
                });

            modelBuilder.Entity("StudentManagementSystem.DAL.Models.RegistrationRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("CreatedStudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("MajorId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ProcessedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ProcessedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RequestId");

                    b.ToTable("RegistrationRequests");
                });

            modelBuilder.Entity("StudentManagementSystem.DAL.Models.Semester", b =>
                {
                    b.Property<int>("SemesterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SemesterId"));

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SemesterName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SemesterNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("SemesterId");

                    b.ToTable("Semesters");

                    b.HasData(
                        new
                        {
                            SemesterId = 1,
                            AcademicYear = "2024-2025",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2024, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SemesterName = "Kỳ 1",
                            SemesterNumber = 1,
                            StartDate = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed"
                        },
                        new
                        {
                            SemesterId = 2,
                            AcademicYear = "2024-2025",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2025, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SemesterName = "Kỳ 2",
                            SemesterNumber = 2,
                            StartDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active"
                        },
                        new
                        {
                            SemesterId = 3,
                            AcademicYear = "2024-2025",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2025, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SemesterName = "Kỳ 3",
                            SemesterNumber = 3,
                            StartDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Upcoming"
                        },
                        new
                        {
                            SemesterId = 4,
                            AcademicYear = "2025-2026",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2025, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SemesterName = "Kỳ 4",
                            SemesterNumber = 4,
                            StartDate = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Upcoming"
                        },
                        new
                        {
                            SemesterId = 5,
                            AcademicYear = "2025-2026",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2026, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SemesterName = "Kỳ 5",
                            SemesterNumber = 5,
                            StartDate = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Upcoming"
                        },
                        new
                        {
                            SemesterId = 6,
                            AcademicYear = "2025-2026",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2026, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SemesterName = "Kỳ 6",
                            SemesterNumber = 6,
                            StartDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Upcoming"
                        },
                        new
                        {
                            SemesterId = 7,
                            AcademicYear = "2026-2027",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2026, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SemesterName = "Kỳ 7",
                            SemesterNumber = 7,
                            StartDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Upcoming"
                        },
                        new
                        {
                            SemesterId = 8,
                            AcademicYear = "2026-2027",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2027, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SemesterName = "Kỳ 8",
                            SemesterNumber = 8,
                            StartDate = new DateTime(2026, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Upcoming"
                        },
                        new
                        {
                            SemesterId = 9,
                            AcademicYear = "2026-2027",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2027, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SemesterName = "Kỳ 9",
                            SemesterNumber = 9,
                            StartDate = new DateTime(2027, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Upcoming"
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.DAL.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("CGPA")
                        .HasColumnType("decimal(4,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentSemester")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("MajorId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("StudentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MajorId");

                    b.HasIndex("StudentCode")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("StudentManagementSystem.DAL.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BalanceAfter")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BalanceBefore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("EnrollmentId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("TransactionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("TransactionId");

                    b.HasIndex("StudentId");

                    b.HasIndex("WalletId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("StudentManagementSystem.DAL.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InstructorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("InstructorId")
                        .IsUnique()
                        .HasFilter("[InstructorId] IS NOT NULL");

                    b.HasIndex("StudentId")
                        .IsUnique()
                        .HasFilter("[StudentId] IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PasswordHash = "$2a$11$fWslbqtaua.sdAkM2RHkxerKttU1Pzj.aaQ1wUZ3I5GUql73iNzwO",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.DAL.Models.Wallet", b =>
                {
                    b.Property<int>("WalletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WalletId"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("WalletId");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("StudentManagementSystem.DAL.Models.Course", b =>
                {
                    b.HasOne("StudentManagementSystem.DAL.Models.Major", "Major")
                        .WithMany("Courses")
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagementSystem.DAL.Models.Course", "PrerequisiteCourse")
                        .WithMany()
                        .HasForeignKey("PrerequisiteCourseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Major");

                    b.Navigation("PrerequisiteCourse");
                });

            modelBuilder.Entity("StudentManagementSystem.DAL.Models.CourseClass", b =>
                {
                    b.HasOne("StudentManagementSystem.DAL.Models.Course", "Course")
                        .WithMany("CourseClasses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagementSystem.DAL.Models.Instructor", "Instructor")
                        .WithMany("CourseClasses")
                        .HasForeignKey("InstructorId");

                    b.HasOne("StudentManagementSystem.DAL.Models.Semester", "Semester")
                        .WithMany("CourseClasses")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Instructor");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("StudentManagementSystem.DAL.Models.Enrollment", b =>
                {
                    b.HasOne("StudentManagementSystem.DAL.Models.CourseClass", "CourseClass")
                        .WithMany("Enrollments")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentManagementSystem.DAL.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentManagementSystem.DAL.Models.Semester", null)
                        .WithMany("Enrollments")
                        .HasForeignKey("SemesterId");

                    b.HasOne("StudentManagementSystem.DAL.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("CourseClass");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentManagementSystem.DAL.Models.Grade", b =>
                {
                    b.HasOne("StudentManagementSystem.DAL.Models.Course", "Course")
                        .WithMany("Grades")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentManagementSystem.DAL.Models.Enrollment", "Enrollment")
                        .WithOne("Grade")
                        .HasForeignKey("StudentManagementSystem.DAL.Models.Grade", "EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagementSystem.DAL.Models.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Enrollment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentManagementSystem.DAL.Models.InstructorAssignment", b =>
                {
                    b.HasOne("StudentManagementSystem.DAL.Models.Course", "Course")
                        .WithMany("InstructorAssignments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagementSystem.DAL.Models.Instructor", "Instructor")
                        .WithMany("InstructorAssignments")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("StudentManagementSystem.DAL.Models.Invoice", b =>
                {
                    b.HasOne("StudentManagementSystem.DAL.Models.Student", "Student")
                        .WithMany("Invoices")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentManagementSystem.DAL.Models.Notification", b =>
                {
                    b.HasOne("StudentManagementSystem.DAL.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudentManagementSystem.DAL.Models.PendingEnrollment", b =>
                {
                    b.HasOne("StudentManagementSystem.DAL.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentManagementSystem.DAL.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentManagementSystem.DAL.Models.Student", b =>
                {
                    b.HasOne("StudentManagementSystem.DAL.Models.Major", "Major")
                        .WithMany("Students")
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Major");
                });

            modelBuilder.Entity("StudentManagementSystem.DAL.Models.Transaction", b =>
                {
                    b.HasOne("StudentManagementSystem.DAL.Models.Student", "Student")
                        .WithMany("Transactions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentManagementSystem.DAL.Models.Wallet", "Wallet")
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("StudentManagementSystem.DAL.Models.User", b =>
                {
                    b.HasOne("StudentManagementSystem.DAL.Models.Instructor", "Instructor")
                        .WithOne("User")
                        .HasForeignKey("StudentManagementSystem.DAL.Models.User", "InstructorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StudentManagementSystem.DAL.Models.Student", "Student")
                        .WithOne("User")
                        .HasForeignKey("StudentManagementSystem.DAL.Models.User", "StudentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Instructor");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentManagementSystem.DAL.Models.Wallet", b =>
                {
                    b.HasOne("StudentManagementSystem.DAL.Models.Student", "Student")
                        .WithOne("Wallet")
                        .HasForeignKey("StudentManagementSystem.DAL.Models.Wallet", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentManagementSystem.DAL.Models.Course", b =>
                {
                    b.Navigation("CourseClasses");

                    b.Navigation("Enrollments");

                    b.Navigation("Grades");

                    b.Navigation("InstructorAssignments");
                });

            modelBuilder.Entity("StudentManagementSystem.DAL.Models.CourseClass", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("StudentManagementSystem.DAL.Models.Enrollment", b =>
                {
                    b.Navigation("Grade");
                });

            modelBuilder.Entity("StudentManagementSystem.DAL.Models.Instructor", b =>
                {
                    b.Navigation("CourseClasses");

                    b.Navigation("InstructorAssignments");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudentManagementSystem.DAL.Models.Major", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("StudentManagementSystem.DAL.Models.Semester", b =>
                {
                    b.Navigation("CourseClasses");

                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("StudentManagementSystem.DAL.Models.Student", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Grades");

                    b.Navigation("Invoices");

                    b.Navigation("Transactions");

                    b.Navigation("User");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("StudentManagementSystem.DAL.Models.User", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("StudentManagementSystem.DAL.Models.Wallet", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
